{
 "title": "Federation Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "content": "# CTC SimpliVity \n\n[SimpliVity Demo](https://svt-vcsa.demo.local)\n\n[SimpliVity Infrastructure](https://suo04ctcinf5.demo.local)\n\n\n\n[Administrator: Thomas Beha](mailto:thomas.beha@hpe.com)\n\n\n"
  },
  {
   "title": "Number of Cluster",
   "type": "bargauge",
   "description": "Cluster in this Federation",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "simplivity_cluster{clustermetric=\"Cluster_count\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "# of Nodes",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"Node_count\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "# of VMs",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "simplivity_vm{vmmetric=\"VM_count\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Sample #",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "targets": [
    { "expr": "simplivity_sample_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Sample Runtime",
   "type": "bargauge",
   "description": "Time to gather the sample",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "targets": [
    { "expr": "ConnectorRuntime", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Federation SimpliVity Node State",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"State\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Cluster - IOPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "simplivity_cluster{clustermetric=\"read_iops\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    },
    {
     "expr": "simplivity_cluster{clustermetric=\"write_iops\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    }
   ]
  },
  {
   "title": "Cluster - Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "simplivity_cluster{clustermetric=\"read_latency\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    },
    {
     "expr": "simplivity_cluster{clustermetric=\"write_latency\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    }
   ]
  },
  {
   "title": "Cluster -  Throughput",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "MBps" }
   ],
   "targets": [
    {
     "expr": "simplivity_cluster{clustermetric=\"read_throughput\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    },
    {
     "expr": "simplivity_cluster{clustermetric=\"write_throughput\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    }
   ]
  },
  {
   "title": "Cluster - Free Space",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "simplivity_cluster{clustermetric=\"free_space\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    }
   ]
  },
  {
   "title": "Cluster - Data Efficiency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "simplivity_cluster{clustermetric=\"efficiency_ratio\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    },
    {
     "expr": "simplivity_cluster{clustermetric=\"deduplication_ratio\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    },
    {
     "expr": "simplivity_cluster{clustermetric=\"compression_ratio\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    }
   ]
  },
  {
   "title": "Cluster - Backup Capacity",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "simplivity_cluster{clustermetric=\"local_backup_capacity\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    },
    {
     "expr": "simplivity_cluster{clustermetric=\"remote_backup_capacity\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    }
   ]
  }
 ]
}