{
 "title": "SimpliVIty Cluster Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Selection" }
  ]
 },
 "panels": [
  {
   "title": "SimpliVIty Demo Cluster Latency",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "simplivity_cluster{clustermetric=\"read_latency\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    },
    {
     "expr": "simplivity_cluster{clustermetric=\"write_latency\"} ",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    }
   ]
  },
  {
   "title": "SimpliVIty Demo Cluster Throughput",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "simplivity_cluster{clustermetric=\"read_throughput\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    },
    {
     "expr": "simplivity_cluster{clustermetric=\"write_throughput\"} ",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    }
   ]
  },
  {
   "title": "SimpliVIty Demo Cluster IOPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "simplivity_cluster{clustermetric=\"read_iops\"}",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    },
    {
     "expr": "simplivity_cluster{clustermetric=\"write_iops\"} ",
     "legendFormat": "{{clustername}}_{{clustermetric}}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "simplivity_cluster{clustermetric=\"used_capacity\"}",
     "legendFormat": "{{clustername}}"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "simplivity_cluster{clustermetric=\"free_space\"}",
     "legendFormat": "{{clustername}}"
    }
   ]
  },
  {
   "title": "Allocated Capacity",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "simplivity_cluster{clustermetric=\"allocated_capacity\"}",
     "legendFormat": "{{clustername}}"
    }
   ]
  }
 ]
}