{
 "title": "SimpliVity-Node-Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Node IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"read_iops\"}",
     "legendFormat": "{{nodename}}_{{nodemetric}}"
    },
    {
     "expr": "simplivity_node{nodemetric=\"write_iops\"}",
     "legendFormat": "{{nodename}}_{{nodemetric}}"
    }
   ]
  },
  {
   "title": "Node Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"read_latency\"}",
     "legendFormat": "{{nodename}}_{{nodemetric}}"
    },
    {
     "expr": "simplivity_node{nodemetric=\"write_latency\"}",
     "legendFormat": "{{nodename}}_{{nodemetric}}"
    }
   ]
  },
  {
   "title": "Node Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "MBps" }
   ],
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"read_throughput\"}",
     "legendFormat": "{{nodename}}_{{nodemetric}}"
    },
    {
     "expr": "simplivity_node{nodemetric=\"write_throughput\"}",
     "legendFormat": "{{nodename}}_{{nodemetric}}"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"free_space\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Used Capacity ",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"used_capacity\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Stored Virtual Machine Data",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"stored_virtual_machine_data\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Efficiency Ratio",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"efficiency_ratio\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Deduplication Ratio",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"deduplication_ratio\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Compression Ratio",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"compression_ratio\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Allocated Capacity",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"allocated_capacity\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Local Backup Capacity",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"local_backup_capacity\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Remote Backup Capacity",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "simplivity_node{nodemetric=\"remote_backup_capacity\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}